from __future__ import annotations

S27_V2_REPLAY_PLANNING_READY_STATUS = "S27_ZN_V2_TRUST_ROOT_PROVENANCE_DESIGN_PLANNING_READY_ONLY"
S27_V2_TRUSTED_REPLAY_BUNDLE_STATUS = "S27_V2_TRUSTED_REPLAY_BUNDLE"
STRUCTURAL_SCHEMA_ONLY_NOT_SOURCE_EVIDENCE = "STRUCTURAL_SCHEMA_ONLY_NOT_SOURCE_EVIDENCE"
S27_V2_STRATEGY_ID = "S27_V2_ZN"
S27_V2_INSTRUMENT = "ZN"
S27_V2_LANE = "SOURCE_NATIVE_FUTURES"

S27_V2_REPLAY_NON_AUTHORIZATION = (
    "NO_PROVIDER_API",
    "NO_DOWNLOAD",
    "NO_FILE_PARSING_OR_REPLAY_RUNNER_EXECUTION",
    "NO_DIAGNOSTIC",
    "NO_BACKTEST",
    "NO_OOS_LOCKBOX_FORWARD",
    "NO_GIT_STAGING_COMMIT_PUSH",
    "NO_ADAPTER_DEPLOYMENT_TRADING_PROMOTION",
)

BLOCKED_CANONICAL_SERIALIZATION = "BLOCKED_SOURCE_UNRESOLVED_CANONICAL_SERIALIZATION_AND_HASH_POLICY"
BLOCKED_TRUST_ROOT = "BLOCKED_SOURCE_UNRESOLVED_NON_FORGEABLE_TRUST_ROOT"
BLOCKED_SOURCE_UNIVERSE = "BLOCKED_SOURCE_UNRESOLVED_SOURCE_UNIVERSE_AND_ROW_LOCATOR_HASHES"
BLOCKED_LEVEL_COMPATIBILITY = "BLOCKED_SOURCE_UNRESOLVED_DAILY_HOURLY_LEVEL_COMPATIBILITY_PROOF"
BLOCKED_RUNTIME_HISTORY = "BLOCKED_SOURCE_UNRESOLVED_FORECAST_HISTORY_STATE_HASHES"
BLOCKED_SIGMA = "BLOCKED_SOURCE_UNRESOLVED_STRATEGY3_SIGMA_PROVENANCE"
BLOCKED_TICK = "BLOCKED_SOURCE_UNRESOLVED_ZN_TICK_ROUNDING_POLICY"
BLOCKED_INITIAL_POSITION = "BLOCKED_SOURCE_UNRESOLVED_INITIAL_POSITION_POLICY"
BLOCKED_WORKING_LIMIT_LIFECYCLE = "BLOCKED_SOURCE_UNRESOLVED_WORKING_LIMIT_LIFECYCLE"
BLOCKED_OVERNIGHT = "BLOCKED_SOURCE_UNRESOLVED_OVERNIGHT_RECOMPUTED_TARGET"
BLOCKED_ROLL_BRIDGE = "BLOCKED_SOURCE_UNRESOLVED_NONZERO_ROLL_BRIDGE"
BLOCKED_COST_SCHEMA = "BLOCKED_SOURCE_UNRESOLVED_TRUSTED_COST_ROW_AMOUNT_UNIT_SCHEMA"
BLOCKED_CAPACITY_SPEED = "BLOCKED_SOURCE_UNRESOLVED_CAPACITY_SPEED_ELIGIBILITY"
BLOCKED_EVIDENCE_MANIFEST = "BLOCKED_SOURCE_UNRESOLVED_STALE_EVIDENCE_SUPERSESSION_MANIFEST"

REQUIRED_UNRESOLVED_GATE_LABELS = (
    BLOCKED_CANONICAL_SERIALIZATION,
    BLOCKED_TRUST_ROOT,
    BLOCKED_SOURCE_UNIVERSE,
    BLOCKED_LEVEL_COMPATIBILITY,
    BLOCKED_RUNTIME_HISTORY,
    BLOCKED_SIGMA,
    BLOCKED_TICK,
    BLOCKED_INITIAL_POSITION,
    BLOCKED_WORKING_LIMIT_LIFECYCLE,
    BLOCKED_OVERNIGHT,
    BLOCKED_ROLL_BRIDGE,
    BLOCKED_COST_SCHEMA,
    BLOCKED_CAPACITY_SPEED,
    BLOCKED_EVIDENCE_MANIFEST,
)

ARTIFACT_FAMILIES = (
    "SOURCE_INPUT_MANIFEST",
    "DAILY_HOURLY_CONTINUOUS_LEVEL_COMPATIBILITY_LEDGER",
    "RUNTIME_REPLAY_LEDGER_EWMA5_EWMAC_SIGMA_VQM",
    "FORECAST_REPLAY_LEDGER",
    "DESIRED_POSITION_LEDGER",
    "LIMIT_ORDER_LEDGER",
    "MARKET_ORDER_LEDGER",
    "WORKING_ORDER_TRANSITION_LEDGER",
    "REMAINING_LIMIT_ORDER_LEDGER",
    "CANCELED_LIMIT_ORDER_LEDGER",
    "FILL_LEDGER",
    "COMMISSION_LEDGER",
    "SPREAD_COST_LEDGER",
    "PNL_LEDGER",
    "VALIDATION_LEDGER",
    "PROVENANCE_AND_HASH_LEDGER",
    "LOCAL_HOSTILE_AUDIT_RESULT",
)

ACTIVE_EVIDENCE_STATUS_LABEL = "ACTIVE_EVIDENCE"
SUPERSEDED_EVIDENCE_STATUS_LABEL = "SUPERSEDED_EVIDENCE"

REQUIRED_EVIDENCE_MANIFEST_ARTIFACT_TYPES = (
    "SOURCE_LOCK",
    "LOCAL_DATA_CONTRACT",
    "PROVENANCE_DESIGN",
    "RUNNER_IMPLEMENTATION",
    "PARSER_EXTRACTOR_SOURCE",
    "DEPENDENCY_RUNTIME_MANIFEST",
    "REPLAY_CONFIG",
    "SOURCE_INPUT_UNIVERSE_MANIFEST",
    "RAW_SOURCE_FILE_HASH_SET",
    "SOURCE_ROW_BATCH_CONTRACT",
    "SOURCE_ROW_BATCH_SET",
    "SOURCE_ROW_LOCATOR",
    "SOURCE_ROW_SELECTION_AUTHORITY",
    "CANONICAL_SERIALIZATION_POLICY",
    "CANONICAL_SERIALIZATION_SCHEMA",
    "HASH_ALGORITHM_VERSION",
    "FIELD_ORDERING_POLICY",
    "DECIMAL_FLOAT_NORMALIZATION_POLICY",
    "TIMEZONE_NORMALIZATION_POLICY",
    "ROW_ORDERING_COLLATION_POLICY",
    "NULL_MISSING_SENTINEL_POLICY",
    "STRING_ENCODING_POLICY",
    "HASH_PAYLOAD_VERSION_POLICY",
    "SESSION_CALENDAR_POLICY",
    "ROLL_CALENDAR_POLICY",
    "TICK_ROUNDING_POLICY",
    "COMMISSION_POLICY",
    "SPREAD_UNIT_POLICY",
    "CONTRACT_MULTIPLIER_CURRENCY_POLICY",
    "DAILY_HOURLY_COMPATIBILITY_POLICY",
    "STALE_EVIDENCE_SUPERSESSION_MANIFEST",
)
