"""First-spine machinery for synthetic conformance tests."""

from .m0 import (
    BackAdjustmentSpec,
    BarConvention,
    CarverBlocked,
    CompletedBar,
    ContractSpec,
    CostSourceSpec,
    LaneClass,
    RollRuleSpec,
    SessionCalendarSpec,
    SourceRulePlaceholder,
    SourceRuleStatus,
)
from .m1 import RoundingPolicy, SizingInput, SizingResult, TimedValue, size_contracts
from .continuous import ContinuousContractRuleSet, ContinuousSeriesRequest, build_continuous_back_adjusted_series
from .daily_bars import (
    CompletedDailyMarketBar,
    DailyDerivationSession,
    derive_completed_daily_from_minute_export,
    derive_completed_daily_from_web_chart,
)
from .m3 import PortfolioLeg, PortfolioSpec, p01_risk_parity, p02_all_weather
from .minute_export import (
    DEFAULT_MINUTE_EXPORT_QUARANTINE,
    EXPECTED_MINUTE_EXPORT_HEADER,
    MinuteBar,
    MinuteExportSpec,
    parse_minute_export_file,
    parse_minute_export_text,
)
from .s03 import S03RiskConfig, S03RiskEstimate, SyntheticDailyPrice, estimate_s03_annual_risk
from .web_chart_api import (
    ALLOWED_CHART_ENDPOINTS,
    DEFAULT_WEB_CHART_QUARANTINE,
    LOCKED_WEB_CHART_PROVIDER_SYMBOLS,
    MAX_SYNTHETIC_CHART_ELEMENTS,
    ChartBarType,
    LockedWebChartSymbol,
    WebChartBar,
    WebChartProbePlan,
    WebChartRequest,
    WebChartSymbol,
    assert_safe_web_chart_endpoint,
    normalize_web_chart_response_file,
    normalize_web_chart_response,
    web_chart_response_request_binding,
)
from .portfolio_conformance import (
    PortfolioProviderMappingRow,
    ProviderMappingStatus,
    portfolio_conformance_from_daily_bars,
    portfolio_web_chart_mapping_status,
    require_locked_portfolio_web_chart_mapping,
)

__all__ = [
    "BackAdjustmentSpec",
    "BarConvention",
    "CarverBlocked",
    "CompletedBar",
    "CompletedDailyMarketBar",
    "ContractSpec",
    "ContinuousContractRuleSet",
    "ContinuousSeriesRequest",
    "CostSourceSpec",
    "DailyDerivationSession",
    "DEFAULT_MINUTE_EXPORT_QUARANTINE",
    "DEFAULT_WEB_CHART_QUARANTINE",
    "ALLOWED_CHART_ENDPOINTS",
    "ChartBarType",
    "LaneClass",
    "LOCKED_WEB_CHART_PROVIDER_SYMBOLS",
    "MAX_SYNTHETIC_CHART_ELEMENTS",
    "LockedWebChartSymbol",
    "EXPECTED_MINUTE_EXPORT_HEADER",
    "MinuteBar",
    "MinuteExportSpec",
    "PortfolioLeg",
    "PortfolioProviderMappingRow",
    "PortfolioSpec",
    "ProviderMappingStatus",
    "RoundingPolicy",
    "RollRuleSpec",
    "S03RiskConfig",
    "S03RiskEstimate",
    "SessionCalendarSpec",
    "SourceRulePlaceholder",
    "SourceRuleStatus",
    "SyntheticDailyPrice",
    "SizingInput",
    "SizingResult",
    "TimedValue",
    "WebChartBar",
    "WebChartProbePlan",
    "WebChartRequest",
    "WebChartSymbol",
    "assert_safe_web_chart_endpoint",
    "build_continuous_back_adjusted_series",
    "derive_completed_daily_from_minute_export",
    "derive_completed_daily_from_web_chart",
    "estimate_s03_annual_risk",
    "normalize_web_chart_response",
    "normalize_web_chart_response_file",
    "web_chart_response_request_binding",
    "p01_risk_parity",
    "p02_all_weather",
    "portfolio_conformance_from_daily_bars",
    "portfolio_web_chart_mapping_status",
    "parse_minute_export_file",
    "parse_minute_export_text",
    "require_locked_portfolio_web_chart_mapping",
    "size_contracts",
]
